FROM maven:3-jdk-11 as builder
ADD . /app
WORKDIR /app
RUN mvn clean install


FROM openjdk:11-jdk
COPY --from=builder "/app/target/Vaques-1.0-SNAPSHOT.jar" app.jar
EXPOSE 4567
CMD [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
